// packages/taro/vue/LuckyScratch.vue
<template>
  <canvas
    v-if="showCanvas"
    type="2d"
    id="lucky-scratch"
    :style="{ width, height }"
  />
</template>

<script>
import Taro from '@tarojs/taro'
import { LuckyScratch } from 'lucky-scratch'
import { changeUnits } from '../utils'

export default {
  name: 'LuckyScratch',
  props: {
    width: {
      type: String,
      default: '300px'
    },
    height: {
      type: String,
      default: '150px'
    },
    mask: {
      type: Object,
      default: () => ({
        type: 'color',
        color: '#ccc'
      })
    },
    scratch: {
      type: Object,
      default: () => ({
        radius: 20,
        percent: 0.5
      })
    }
  },
  data() {
    return {
      lucky: null,
      showCanvas: true
    }
  },
  watch: {
    mask: {
      handler(newVal) {
        if (this.lucky) {
          this.lucky.mask = newVal
          this.init()
        }
      },
      deep: true
    },
    scratch: {
      handler(newVal) {
        if (this.lucky) {
          this.lucky.scratch = newVal
        }
      },
      deep: true
    }
  },
  mounted() {
    this.initLucky()
  },
  methods: {
    initLucky() {
      const query = Taro.createSelectorQuery()
      query.select('#lucky-scratch').fields({ node: true, size: true }).exec((res) => {
        if (!res[0] || !res[0].node) {
          return console.error('lucky-scratch 获取不到 canvas 标签')
        }
        const canvas = res[0].node
        const dpr = Taro.getSystemInfoSync().pixelRatio
        const ctx = canvas.getContext('2d')
        canvas.width = res[0].width * dpr
        canvas.height = res[0].height * dpr
        ctx.scale(dpr, dpr)

        this.lucky = new LuckyScratch(
          {
            flag: 'TARO',
            ctx,
            dpr,
            setTimeout,
            clearTimeout,
            setInterval,
            clearInterval,
            unitFunc: (num, unit) => changeUnits(num + unit)
          },
          {
            width: res[0].width,
            height: res[0].height,
            mask: this.mask,
            scratch: this.scratch,
            onceBeforeStart: async () => {
              const result = await new Promise((resolve) => {
                this.$emit('once-before-start', resolve)
              })
              return result !== false
            },
            beforeStart: async () => {
              const result = await new Promise((resolve) => {
                this.$emit('before-start', resolve)
              })
              return result !== false
            },
            start: () => {
              this.$emit('start')
            },
            end: () => {
              this.$emit('end')
            },
            success: (progress) => {
              this.$emit('success', progress)
            },
            afterInit: () => {
              this.$emit('ready')
            }
          }
        )
      })
    },
    init() {
      this.lucky && this.lucky.init()
    },
    setDisabled(disabled) {
      this.lucky && this.lucky.setDisabled(disabled)
    }
  }
}
</script>

// packages/react/src/components/LuckyScratch.js
import React from 'react'
import { LuckyScratch as Scratch } from 'lucky-canvas'
import { name, version } from '../../package.json'

export default class LuckyScratch extends React.Component {
  constructor (props) {
    super(props)
    this.myLucky = React.createRef()
    this.lucky = undefined
  }
  componentDidMount () {
    // 当前已经有实例时，不再进行，解决在`react18 + strictMode`下组件componentDidMount会被触发两次的问题
    if (this.lucky) {
      return
    }
    this.myLucky.current.setAttribute('package', `${name}@${version}`)
    try {
      this.initLucky()
    } catch (err) {
      this.props.onError && this.props.onError(err)
    } finally {
      this.props.onFinally && this.props.onFinally()
    }
  }
  componentDidUpdate (prevProps) {
    if (!this.lucky) return
    if (this.props.width !== prevProps.width) {
      this.lucky.width = this.props.width
    }
    if (this.props.height !== prevProps.height) {
      this.lucky.height = this.props.height
    }
    if (JSON.stringify(this.props.mask) !== JSON.stringify(prevProps.mask)) {
      this.lucky.mask = this.props.mask
      this.init()
    }
    if (JSON.stringify(this.props.scratch) !== JSON.stringify(prevProps.scratch)) {
      this.lucky.scratch = this.props.scratch
    }
  }
  initLucky () {
    this.lucky = new Scratch({
      flag: 'WEB',
      divElement: this.myLucky.current,
      rAF: window.requestAnimationFrame,
      setTimeout: window.setTimeout,
      setInterval: window.setInterval,
      clearTimeout: window.clearTimeout,
      clearInterval: window.clearInterval,
    }, {
      width: this.props.width,
      height: this.props.height,
      mask: this.props.mask,
      scratch: this.props.scratch,
      onceBeforeStart: async () => {
        if (this.props.onOnceBeforeStart) {
          const result = await new Promise((resolve) => {
            this.props.onOnceBeforeStart(resolve)
          })
          return result !== false
        }
        return true
      },
      beforeStart: async () => {
        if (this.props.onBeforeStart) {
          const result = await new Promise((resolve) => {
            this.props.onBeforeStart(resolve)
          })
          return result !== false
        }
        return true
      },
      start: (...rest) => {
        this.props.onStart && this.props.onStart(...rest)
      },
      end: (...rest) => {
        this.props.onEnd && this.props.onEnd(...rest)
      },
      success: (progress) => {
        this.props.onSuccess && this.props.onSuccess(progress)
      },
      afterInit: () => {
        this.props.onReady && this.props.onReady()
      },
    })
  }
  init (...rest) {
    this.lucky && this.lucky.init(...rest)
  }
  setDisabled (disabled) {
    this.lucky && this.lucky.setDisabled(disabled)
  }
  render () {
    return <div ref={this.myLucky}></div>
  }
}

LuckyScratch.defaultProps = {
  width: '300px',
  height: '150px',
  mask: {
    type: 'color',
    color: '#ccc',
  },
  scratch: {
    radius: 20,
    percent: 0.5,
  },
}
